One Window Stats
ajstarna/poker-spirit pull request #2
Opened 2020-06-04 02:48 UTC by mdfeist

Fixed stats for _4_bet_str and added a view to show all the stats in one window. Would like to add the ability to show both versions of the HUD at the same time.

2020-06-04 03:08 UTC, solinas commented on poker-spirit/hud.py
> +        PokerStarsGameIO
this line looks fishy

2020-06-04 03:17 UTC, ajstarna requested changes

2020-06-04 03:17 UTC, ajstarna commented on poker-spirit/hud.py
> +    def merge_current_and_career_stats(self, game, career_stats):
seems like this method is the main thing we need in both classes? But doesn't use self. Lets make it just a function?

2020-06-04 03:17 UTC, ajstarna commented on poker-spirit/hud.py
> +        PokerStarsGameIO
weird?

2020-06-04 03:17 UTC, ajstarna commented on poker-spirit/hud.py
> +class PlayerWindowsManager(PlayerStatsWindow):
i feel like the manager shouldn't inherit. to me the manager is a contain of multiple windows.

2020-06-04 03:17 UTC, ajstarna commented on poker-spirit/hud.py
> +class AllPlayerWindowManager(PlayerStatsWindow):
i dont agree that this is a "manager" is it? Maybe just "AllPlayerStatsWindow"?

2020-06-04 03:17 UTC, ajstarna commented on poker-spirit/analyze_hands.py
> +            return f'4-Bet = {stats["4_bet"]}/{stats["4_bet_opp"]} = {round(100*stats["4_bet"]/stats["4_bet_opp"], 1)}'
good catch

2020-06-04 03:20 UTC, ajstarna commented on poker-spirit/hud.py
> +class AllPlayerWindowManager(PlayerStatsWindow):
looking at the whole code again maybe im wrong i dunno

2020-06-05 03:26 UTC, ajstarna approved these changes

2020-06-05 03:26 UTC, merged